# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Tests

on: [push]

jobs:
  unit_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies
        run: poetry install --with test --no-interaction --no-ansi
      - name: Build
        run: poetry build
      - name: Run unit and integration tests
        env:
          NVM_API_KEY: ${{ secrets.NVM_API_KEY }}
          NVM_API_KEY2: ${{ secrets.NVM_API_KEY2 }}
        run: poetry run pytest -m "not slow" -v -s

  e2e:
    runs-on: ubuntu-latest
    needs: unit_integration
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies
        run: poetry install --with test --no-interaction --no-ansi
      - name: Build
        run: poetry build
      - name: Run E2E tests (allowed to be flaky)
        env:
          NVM_API_KEY: ${{ secrets.NVM_API_KEY }}
          NVM_API_KEY2: ${{ secrets.NVM_API_KEY2 }}
        run: poetry run pytest -m "slow" -v -s
